apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: test-namespace
commonLabels:
  app: test-app

configMapGenerator:
  - name: configmap
    behavior: create
    envs:
    - prod-config

resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml
