apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-namespace
commonLabels:
  app: test-app

generatorOptions:
  disableNameSuffixHash: true

resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml